### ISSUE TITLE
missing <project_name>_truth.json

### ISSUE THREAD

**Issue by Emily-zcy** [PPPI/a-m#3]
Dear author,
I found that the <project_name>_truth.json is missing, so I can't run your code. <project_name>_truth.json is not provided in the Corpora dataset. How do I generate it? I will be grateful for your help.

**Comment by PPPI** [comment]
On quick inspection, indeed the files are missing. As I have since changed institutions, I do not have access to the servers where the experiment was run to extract from there. So instead what I can offer is the development dataset that I have on my machine.

The `_r_%0.2f_truth.json` are noise-injected files used in ablation studies.
dev_data: https://drive.proton.me/urls/HKSVDW0XS4#ymBejSmyWwrn

**Comment by Emily-zcy** [comment]
I'm sorry to hear that, but thank you for your help anyway.

**Comment by PPPI** [comment]
I am still looking through personal archives, I may be able to regenerate the files over the weekend if I recover the original heuristic linking code.

The core way the dataset was constructed was using the sha and issue number match from: https://github.com/PPPI/a-m/blob/master/Util/heuristic_methods.py 
 - if an issue has a sha that resolves to a commit associated with a PR, add that as a link; 
 - if an issue has an `#nnnn` pattern that resolves to a valid issue or PR number, link;
 - ignore links to `#1` as those are typically false flags.

I glanced over to your profile and noticed the GCN2defect repo, if you are looking for a way to generate data for that, I think SZZ might be a better bet: https://github.com/wogscpar/SZZUnleashed

**Comment by Emily-zcy** [comment]
Thank you very much for your information, which has helped me a lot!  Best wishes for you.
